[project]
name = "st-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.5",
    "pycairo>=1.28.0",
    "scikit-image>=0.25.2",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "."}
ext-modules = [
    {name = "utils", sources = ["utils.c"]},
    {name = "cbezier", sources = ["cbezier.c"], include-dirs = ["numpy"]},
]


[dependency-groups]
dev = [
    "cython>=3.2.3",
    "snakeviz>=2.2.2",
]
